docs/ja/perception/label.md
perception_eval/perception_eval/common/label.py
perception_eval/test/common/test_label.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

refactor: update to support upper case

---

perception_eval/perception_eval/common/status.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: add new visibility type unavailable

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.0 -> v1.0.1
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.0.1

---

perception_eval/perception_eval/tool/perception_performance_analyzer.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(PerceptionPerformanceAnalyzer): fix the number of frame

---

docs/ja/sensing/design.md
perception_eval/perception_eval/config/sensing_evaluation_config.py
perception_eval/perception_eval/evaluation/sensing/sensing_frame_config.py
perception_eval/perception_eval/manager/sensing_evaluation_manager.py
perception_eval/test/sensing_lsim.py

Add support of specifying evaluation config per frame.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat(sensing_evaluation): add support of frame evaluation config

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.1 -> v1.0.2
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): releasev1.0.2

---

.github/workflows/build-and-test-mock.yaml
.github/workflows/build-and-test.yaml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci(github-actions): specify update-20.04

---

.github/workflows/build-and-test-mock.yaml
.github/workflows/build-and-test.yaml

- Add test with Python3.10
- Remove requirements.txt and update pyproject.toml
- Remove test with Python3.7.11
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci!: add support of testing with python 3.10

---

docs/en/perception/label.md
docs/ja/perception/label.md
perception_eval/perception_eval/common/label.py

Add new labels.
Related to https://github.com/tier4/autoware_perception_evaluation/issues/18
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat(label): add new labels

---

perception_eval/test/perception_lsim.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: fix wrong input name

---

README.md

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

docs(readme): add sample usage in README

---

README.md
docs/en/common.md
docs/ja/common.md
perception_eval/perception_eval/common/dataset.py
perception_eval/perception_eval/common/dataset_utils.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

refactor(FrameGroundTruth): update to keep raw data as numpy array

---

perception_eval/perception_eval/common/label.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: typo of TrafficLightLabel

---

perception_eval/test/perception_lsim2d.py

- [] Prediction
- update sample implementation
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: update sample 2d perception implementation

---

perception_eval/perception_eval/evaluation/metrics/detection/tp_metrics.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(tracking): avoid runtime error

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.3
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): v1.0.2 -> v1.0.3

---

perception_eval/perception_eval/evaluation/metrics/detection/map.py

- Fixed a problem that the strings that should be f-strings are ordinary strings and not formatted.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: f-strings

---

perception_eval/perception_eval/common/status.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(FrameID): fix typo

---

perception_eval/perception_eval/common/object.py
perception_eval/perception_eval/common/point.py
perception_eval/perception_eval/manager/sensing_evaluation_manager.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(sensing): resolve bug for cropping pointcloud with object

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.3 -> v1.0.4
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): v1.0.4

---

perception_eval/perception_eval/evaluation/sensing/sensing_frame_result.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(sensing): fix non-detection are evaluation

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.4 -> v1.0.5
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): v1.0.5

---

perception_eval/perception_eval/common/dataset.py
perception_eval/perception_eval/common/label.py
perception_eval/perception_eval/config/_evaluation_config_base.py
perception_eval/perception_eval/visualization/eda_tool.py
perception_eval/test/common/test_label.py
perception_eval/test/eda.py
perception_eval/test/visualization/test_eda_tool.py

Add `traffic_light` to `TrafficLightLabel` class.
For classification, color labels will be used. e.g. green, red, ...
For the other tasks, `traffic_light` will be used.
This is determinzed by LabelConverter() depending on specified evaluation task.
```python
>>> from perception_eval.common.label import LabelConverter
>>> from perception_eval.common.evaluation_task import EvaluationTask
>>> 
>>> label_prefix = "traffic_light"
>>> label_converter = LabelConverter(EvaluationTask.CLASSIFICATION2D, False, label_prefix)
>>> label_converter.convert_label("red")
<TrafficLightLabel.RED: 'red'>
>>> label_converter.convert_label("green")
<TrafficLightLabel.GREEN: 'green'>
>>> label_converter.convert_label("unknown")
<TrafficLightLabel.UNKNOWN: 'unknown'
>>> …
```

feat: add traffic_light to TrafficLightLabel class

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

Release v1.0.5 -> v1.0.6
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): v1.0.6

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(release): v1.0.7

---

perception_eval/perception_eval/evaluation/metrics/detection/ap.py
perception_eval/perception_eval/evaluation/metrics/detection/map.py
perception_eval/test/evaluation/metrics/detection/test_ap.py
perception_eval/test/evaluation/metrics/detection/test_map.py

Fix mAP calculation
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: update calculation of  mAP when its label is not included

---

.github/workflows/semantic-pull-request.yaml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci: update semantic-pull-request

---

perception_eval/perception_eval/tool/perception_analyzer2d.py
perception_eval/perception_eval/tool/perception_analyzer3d.py
perception_eval/perception_eval/visualization/perception_visualizer2d.py
perception_eval/perception_eval/visualization/perception_visualizer3d.py
perception_eval/perception_eval/visualization/sensing_visualizer.py

Update a method `from_scenario()` in `PerceptionAnalyer` and `PerceptionVisualizer`
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: update to create instance from scenario

---

.github/workflows/build-and-test-mock.yaml
.github/workflows/build-and-test.yaml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci: fix poetry version to 1.5.1

---

perception_eval/perception_eval/tool/perception_analyzer2d.py
perception_eval/perception_eval/tool/perception_analyzer3d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(PerceptionAnalyzer): resolve to return empty DataFrame even if at least one label has no TP

---

docs/ja/release_note.md
perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.1.2

---

perception_eval/perception_eval/common/dataset_utils.py

Fix bug in loading size as tuple
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
==================================================Start Tracking==================================================
[2023-11-13 16:07:56,760] [INFO] [dataset.py:104 load_all_datasets] Start to load dataset ['/media/miura/MS950_2T/T4_dataset/DBv2.0/no_2d/1-1']
[2023-11-13 16:07:56,760] [INFO] [dataset.py:113 load_all_datasets] config: load_raw_data: True, evaluation_task: tracking, frame_id: ['map']
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:06<00:00, 32.02it/s]
[2023-11-13 16:08:03,130] [INFO] …

fix: tuple declaration

---

perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.1.5

---

perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: update version to v1.1.6

---

docs/en/perception/label.md
docs/ja/perception/label.md
perception_eval/perception_eval/common/label.py

Add label names will be converted internally.
- `stroller` -> `PEDESTRIAN`
- `motorcycle` -> `MOTORBIKE`
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: add `stroller` and `motorcycle`

---

perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: update version to v1.1.7

---

perception_eval/perception_eval/tool/perception_analyzer2d.py
perception_eval/perception_eval/tool/perception_analyzer3d.py
perception_eval/perception_eval/tool/perception_analyzer_base.py
perception_eval/perception_eval/tool/utils.py

- Add support of analyzing precision, score and error for each distance.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat(perception): update analyzer

---

perception_eval/perception_eval/tool/perception_analyzer_base.py

Refactoring analyzer.filter()
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

refactor: remove useless for loop

---

perception_eval/perception_eval/tool/perception_analyzer_base.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: avoid error if item instance is str

---

perception_eval/perception_eval/tool/perception_analyzer_base.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: avoid error if item is str in `get_ground_truth` and `get_estimation`

---

perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.1.8

---

perception_eval/perception_eval/tool/perception_analyzer_base.py

Related to https://github.com/tier4/autoware_perception_evaluation/issues/133
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix(analyzer): remove statements causing exception

---

perception_eval/perception_eval/tool/perception_analyzer2d.py
perception_eval/perception_eval/tool/perception_analyzer3d.py
perception_eval/perception_eval/tool/perception_analyzer_base.py

- Update error calculation in analyzer
- add distance metric
- update to contain TN and matched FP error
- 
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: update error analisys

---

perception_eval/perception_eval/tool/perception_analyzer3d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: return None if there is no objects in the specified distance range

---

perception_eval/package.xml
pyproject.toml

Release v1.1.9
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.1.9

---

perception_eval/perception_eval/tool/perception_analyzer3d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: transform NN points from map to base link

---

perception_eval/perception_eval/tool/perception_analyzer3d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: disable to plot nn point state

---

perception_eval/package.xml
pyproject.toml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.1.10

---

.cspell.json
.github/workflows/build-and-test.yaml
.github/workflows/cancel-privious-workflows.yaml
.github/workflows/pre-commit.yml
.github/workflows/release-drafter.yaml
.github/workflows/semantic-pull-request.yaml
.github/workflows/spell-check.yaml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci: add workflow timeout

---

.cspell.json
.github/workflows/build-and-test.yaml
.github/workflows/pre-commit.yml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci: update workflow trigger

---

perception_eval/perception_eval/visualization/perception_visualizer3d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: add an option whether to render object tracks in tracking task

---

.github/workflows/semantic-pull-request.yaml
docs/en/common.md
docs/ja/common.md
perception_eval/perception_eval/common/dataset.py
perception_eval/perception_eval/common/dataset_utils.py
perception_eval/perception_eval/common/object.py
perception_eval/perception_eval/common/schema.py
perception_eval/perception_eval/common/transform.py
perception_eval/perception_eval/evaluation/matching/objects_filter.py
perception_eval/perception_eval/evaluation/metrics/detection/tp_metrics.py
perception_eval/perception_eval/evaluation/result/perception_frame_result.py
perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
perception_eval/perception_eval/manager/perception_evaluation_manager.py
perception_eval/perception_eval/manager/sensing_evaluation_manager.py
perception_eval/perception_eval/tool/perception_analyzer3d.py
perception_eval/perception_eval/tool/perception_analyzer_base.py
perception_eval/perception_eval/tool/utils.py
perception_eval/perception_eval/util/debug.py
perception_eval/perception_eval/visualization/perception_visualizer3d.py
perception_eval/test/common/test_transform.py
perception_eval/test/perception_fp_validation_lsim.py
perception_eval/test/perception_lsim.py

Add new classes to handle coordinate transformations as follows:
- `HomogeneousMatrix`: A 4x4 matrix that easily transforms position and orientation.
- `TransformDict`: A container for specific transformation matrices. The key consists of the source and destination frame IDs, which are converted into `TransformKey`. 
For examples:
```python
from perception_eval.common.transform import TransformDict, HomogeneousMatrix
from perception_eval.common.schema import FrameID
ego2map = HomogeneousMatrix(position=[1.0, 0.0, 0.0], rotation=[1.0, 0.0, 0.0], src=FrameID.BASE_LINK, dst=FrameID.MAP)
transforms = TransformDict([ego2map])
position = transforms.transform(key=(FrameID.BASE_LINK, FrameID.MAP), position=[1.0, 0.0, 0.0])
position = transforms.transform(key=(FrameID.MAP, FrameID.BASE_LINK), …
```

feat: add transform matrix

---

docs/en/common.md
docs/ja/common.md
perception_eval/perception_eval/common/dataset.py
perception_eval/perception_eval/common/dataset_utils.py
perception_eval/perception_eval/visualization/perception_visualizer2d.py
perception_eval/perception_eval/visualization/perception_visualizer3d.py
perception_eval/test/sensing_lsim.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

refactor: update the way of loading raw data

---

perception_eval/perception_eval/common/dataset_utils.py
perception_eval/perception_eval/common/transform.py
perception_eval/test/common/test_transform.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: resolve wrong transformation

---

perception_eval/perception_eval/common/dataset_utils.py
perception_eval/perception_eval/common/schema.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

refactor: apply `HomogeneousMatrix` in `_get_box_velocity`

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.1.10 -> v1.2.0
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.0

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.2.0 -> v1.2.1
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.1

---

.github/workflows/semantic-pull-request.yaml

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

ci: remove `timeout-mutes` from `semantic-pull-request` workflow

---

perception_eval/perception_eval/common/dataset_utils.py
perception_eval/perception_eval/common/schema.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

revert: revert #155

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.2

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.2.4
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.4

---

perception_eval/perception_eval/evaluation/matching/object_matching.py
perception_eval/perception_eval/evaluation/result/object_result.py
perception_eval/perception_eval/manager/perception_evaluation_manager.py

Related to https://github.com/tier4/autoware_perception_evaluation/issues/160.
This PR should be merged after https://github.com/tier4/autoware_perception_evaluation/pull/124 has been merged.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: apply `TransformsDict` while generating object results

---

perception_eval/perception_eval/evaluation/result/object_result.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: update to specify transforms

---

perception_eval/perception_eval/common/label.py
perception_eval/perception_eval/config/perception_evaluation_config.py
perception_eval/perception_eval/config/sensing_evaluation_config.py
perception_eval/perception_eval/evaluation/matching/__init__.py
perception_eval/perception_eval/evaluation/matching/object_matching.py
perception_eval/perception_eval/evaluation/matching/objects_filter.py
perception_eval/perception_eval/evaluation/result/object_result.py
perception_eval/perception_eval/manager/perception_evaluation_manager.py
perception_eval/test/config/test_perception_evaluation_config.py
perception_eval/test/evaluation/matching/test_objects_filter.py
perception_eval/test/evaluation/result/test_object_result.py

This feature is related to [TIER IV INTERNAL LINK](https://docs.google.com/spreadsheets/d/1bA8QpG3v4m-9e7Qytllcu7ut55SbSYS20NllP0YtVSY/edit?gid=1871361215#gid=1871361215&range=4:4).
This PR adds following matching policies that allow to match estimations and GTs depending on their label.
- `MatchingLabelPolicy.DEFAULT` ...Default matching policy.
- `MatchingLabelPolicy.ALLOW_UNKNOWN` ...Allow to match unknown labeled estimations and specific labeled GTs.
- `MatchingLabelPolicy.ALLOW_ANY` ...Allow to match any estimations and GTs regardless their labels. 
This PR allows to specify the policy both with previous and new format as follows:
Note that, for backward compatibility, we allow both `allow_matching_unknown: bool` and `matching_label_policy: str` in `evaluation_config_dict`.
```python …
```

feat: add support of matching any labels

---

perception_eval/perception_eval/tool/perception_analyzer_base.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: resolve errors depending on analyzer

---

perception_eval/perception_eval/tool/perception_analyzer2d.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: avoid calculate error if classification task

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.2.5
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.5

---

perception_eval/perception_eval/tool/perception_analyzer3d.py

add velocity norm
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: add velocity norm

---

perception_eval/perception_eval/evaluation/result/perception_frame_result.py
perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
perception_eval/perception_eval/manager/perception_evaluation_manager.py
perception_eval/perception_eval/tool/utils.py
perception_eval/test/perception_lsim.py
perception_eval/test/perception_lsim2d.py

This PR slso enable us to calculate MetricsScore(e.g. mAP) considering `CriticalObjectFilterConfig`.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
https://github.com/tier4/autoware_perception_evaluation/issues/159
update `driving_log_replayer`
I checked if `Ground Truth Num` is also changed when I changed  `CriticalObjectFilterConfig` in local DLR.
dataset : `44bdcf66-c35e-430f-af34-70c503ecf62c`
<details>
<pre>
<code>
Frame:
Total Num: 20
Skipped Frames: []
Skipped Frames Count: 0
Ground Truth Num: 379
mAP: 0.306, mAPH: 0.227 (Center Distance)
|      Label | car(1) |  truck(1) |  bus(1) |  bicycle(1) |  motorbike(1) |  pedestrian(0.5) |
| :--------: | :---: | :---: | :---: | :---: | :---: | :---: |
| Predict_num | 134 | 18 | 14 | 22 | 0 …

feat: integrate critical objects

---

README.md
perception_eval/perception_eval/manager/perception_evaluation_manager.py
perception_eval/test/perception_fp_validation_lsim.py
perception_eval/test/perception_lsim.py
perception_eval/test/perception_lsim2d.py

delete unecessary `ros_critical_ground_truth_objects` by https://github.com/tier4/autoware_perception_evaluation/pull/179
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: delete ros_critical_ground_truth_objects

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.2.6
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.6

---

perception_eval/perception_eval/common/schema.py

Add `CAM_FRONT_LOWER` to `FrameID` enum members.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat: add support of `CAM_FRONT_LOWER` in frame id

---

perception_eval/package.xml
pyproject.toml
setup.cfg

Release v1.2.6 -> v.1.2.7
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.7

---

perception_eval/perception_eval/evaluation/result/object_result.py

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

fix: update to consider uuid while 1st matching of TLR

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.8

---

perception_eval/perception_eval/config/perception_evaluation_config.py
perception_eval/perception_eval/evaluation/result/object_result.py
perception_eval/perception_eval/manager/perception_evaluation_manager.py

This PR add option to perform whether uuid check first or not.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
I have checked this PR on DLR.

feat(perception): add option on TLR in order to perform whether uuid check first or not.

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.9

---

.github/workflows/build-and-test.yaml
pyproject.toml

Add support of Python3.12
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore(deps): add support of python3.12

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: release v1.2.10

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: bump to v1.2.11

---

perception_eval/perception_eval/tool/perception_analyzer3d.py

This PR adds new feature to calcurate error.
- metrics `bev_area`, `v_yaw` (`distance` (center distance))
- statistics `99 percentile`
https://evaluation.ci.tier4.jp/evaluation/reports/008e5731-21fe-575d-a2d2-024dcb13ac21?project_id=prd_jt
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

feat(perception): add new column

---

perception_eval/package.xml
pyproject.toml
setup.cfg

<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: bump to v1.2.12

---

perception_eval/package.xml
pyproject.toml
setup.cfg

This PR releases v1.2.15.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: bump to v1.2.15

---

perception_eval/package.xml
pyproject.toml
setup.cfg

This PR releases v1.3.0 for minor update. The reason why updates the minor is caused by https://github.com/tier4/autoware_perception_evaluation/pull/204
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>

chore: bump to v1.3.0
