perception_eval/perception_eval/common/dataset_utils.py, perception_eval/test/perception_lsim2d.py
Related to https://github.com/tier4/autoware_perception_evaluation/issues/53
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(traffic light):  extract lane ID from instance_name

perception_eval/perception_eval/visualization/eda_tool.py
In eda tool, false positives with high confidence are wrongly calculated. tp_results are passed to filtering function instead of fp_results.
Visual comparison of histograms  before and after the fix (with tp_results and fp_results without a threshold)
=> fix: calculation of fp results with high confidence

perception_eval/perception_eval/common/label/__init__.py, perception_eval/perception_eval/common/label/utils.py, perception_eval/perception_eval/common/schema.py, perception_eval/perception_eval/config/perception_evaluation_config.py, perception_eval/perception_eval/manager/perception_evaluation_manager.py, perception_eval/perception_eval/matching/__init__.py, perception_eval/perception_eval/matching/matching_policy.py, perception_eval/perception_eval/matching/object_matching.py, perception_eval/perception_eval/result/perception/perception_result.py, perception_eval/perception_eval/tool/perception_analyzer2d.py, perception_eval/perception_eval/tool/perception_analyzer3d.py, perception_eval/perception_eval/visualization/perception_visualizer2d.py, perception_eval/perception_eval/visualization/perception_visualizer3d.py, perception_eval/perception_eval/visualization/sensing_visualizer.py, perception_eval/test/matching/test_objects_filter.py, perception_eval/test/perception_fp_validation_lsim.py, perception_eval/test/perception_lsim.py
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> feat: add `MatchingPolicy`

perception_eval/perception_eval/tool/perception_analyzer_base.py
Fix the start scene index as 0 for `PerceptionAnalyzer`.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix: fix to set start scene index as 0

perception_eval/perception_eval/common/dataset.py, perception_eval/perception_eval/common/geometry.py, perception_eval/perception_eval/common/transform.py, perception_eval/test/perception_lsim.py
```shell
get_interpolated_now_frame
[perception_evaluator_node.py-65]     return interpolate_ground_truth_frames(before_frame, after_frame, unix_time)
[perception_evaluator_node.py-65]   File "/home/autoware/pilot-auto/install/perception_eval/local/lib/python3.10/dist-packages/perception_eval/common/dataset.py", line 363, in interpolate_ground_truth_frames
[perception_evaluator_node.py-65]     ego2map_matrix = interpolate_homogeneous_matrix(
[perception_evaluator_node.py-65]   File "/home/autoware/pilot-auto/install/perception_eval/local/lib/python3.10/dist-packages/perception_eval/common/geometry.py", line 44, in interpolate_homogeneous_matrix
[perception_evaluator_node.py-65]     assert matrix_1.shape == matrix_2.shape
[perception_evaluator_node.py-65] AttributeError: …
```
=> fix: resolve invalid attribute access for `HomogeneousMatrix`

perception_eval/perception_eval/common/geometry.py, perception_eval/perception_eval/evaluation/matching/object_matching.py
In accordance with [Flake8(E721)](https://www.flake8rules.com/rules/E721.html), this PR revises to compare type of two objects by `isinstance(obj1, type(obj2))` instead of `type(obj1) == type(obj2)`
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> refactor: not to compare types by `type(...) == type(...)`

perception_eval/perception_eval/tool/perception_analyzer_base.py
- Avoid `ZeroDivisionError` while computing False Discovery Rate.
- Append "unknown" if it is not contained in `target_labels` but some estimations do.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(perception): resolve analyzer errors

perception_eval/perception_eval/tool/perception_analyzer2d.py
change attributes(e.g. self.df["x"]) initialize value in `PerceptionAnalyzer2D` from `None` to `np.nan`.
For now, this repository has error when use traffic light evaluation.
I also checked this PR using DLR.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
This PR is similar to the error within https://github.com/tier4/autoware_perception_evaluation/pull/124
=> fix: initialize attributes when that does not exist

perception_eval/perception_eval/config/perception_evaluation_config.py
Fix max and min distance filter in `PerceptionEvaluationConfig`.
In Before code, if the variable(e.g. `min_distance`) is set to 0, expected condition is not met. Therefore, I fix to check if the variable is `None` or not.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix: max and min distance filter initialization

perception_eval/perception_eval/common/object.py, perception_eval/perception_eval/common/object2d.py
For covariance evaluation, I added pose_covariance and twist_covariance attribute in State in DynamicObjects.
https://tier4.atlassian.net/browse/RT1-8002
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> feat(DynamicObjects): add covariance parameter within dynamic objects

perception_eval/perception_eval/common/dataset_utils.py
This PR includes skipping loading radar pointcloud file during loading dataset.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix: skip loading radar pointcloud

perception_eval/perception_eval/evaluation/matching/objects_filter.py, perception_eval/perception_eval/tool/utils.py
This PR enables to filter objects based on `region` from ego.
If only specify `max_x_position`, it works as usual.
<details>
<pre>
<code>
</code>
</pre>
</details>
already checked by ci
<details>
<pre>
<code>
</code>
</pre>
</details>
- https://github.com/tier4/driving_log_replayer_v2/pull/68
- degradation check https://evaluation.ci.tier4.jp/evaluation/reports/4bef7c82-1343-5098-9475-e82e39c52083?project_id=prd_jt
=> feat(perception): enable to filter based on `region`

perception_eval/perception_eval/common/evaluation_task.py, perception_eval/perception_eval/common/label.py, perception_eval/perception_eval/common/schema.py, perception_eval/perception_eval/common/shape.py, perception_eval/perception_eval/common/status.py, perception_eval/perception_eval/tool/utils.py
This PR adds function `__hash__` in class based on `Enum` and having `__eq__`.
**Background**
The hash (return value by `hash()`) is `None` if the class overwrite `__eq__` and does not define `__hash__` .
This behavior causes it is impossible to use as key of dict.
So I made this PR.
reference: https://docs.python.org/3.13/reference/datamodel.html#object.__hash__
Actually, there is no usecase to use hash now (like key of dict).
https://evaluation.ci.tier4.jp/evaluation/reports/af8b4abd-6042-5df2-838c-8286ea6363d4?project_id=prd_jt
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(perception): re-setting `__hash__` to use `__eq__`

perception_eval/perception_eval/common/object.py, perception_eval/perception_eval/evaluation/matching/object_matching.py
Flip the estimated object if yaw difference between GT and estimated object is bigger than 90 deg. (And fix how to calcurate yaw diff following code docs)
Before implementation, GT and estimated object are evaluated on same surface. But if there is large yaw difference(like 180 deg) between GT and estimated object, it is impossible to measure each nearest surface.
**Implementation Transfer Note**
Before https://github.com/tier4/autoware_perception_evaluation/pull/124
- measure each nearest surface
- there is probability that selection of nearest surface become unstable on each objects. 
- assume GT and estimated object exist near w/o large error. It is possible to select the left surface on GT but select the right surface on estimated objects caused by ego and objects position.
After …
=> fix(perception): fix plane distance when there is yaw difference between gt and est

perception_eval/perception_eval/evaluation/matching/object_matching.py
This PR fix calcuration of plane_distance caused by https://github.com/tier4/autoware_perception_evaluation/pull/208.
And chore (corners do not need to add first points) and delete unnecessary assignment.
Description is below image.
If there is yaw difference of pi/2, it is necessary to align the order of gt corners. but I do not consider it (concretely correct implementation is reverse-rclockwise from the upper left, but my implementation is clockwise from the upper right.).
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(perception): fix plane distance about bbox dimension when there is yaw difference between gt and est

perception_eval/perception_eval/common/threshold.py, perception_eval/perception_eval/evaluation/matching/objects_filter.py, perception_eval/perception_eval/evaluation/metrics/detection/ap.py, perception_eval/perception_eval/evaluation/metrics/tracking/clear.py, perception_eval/perception_eval/evaluation/result/object_result.py
This PR fixes the way of retrieving matchable threshold when GT label is `false_positive`.
In the case of GT  label is `false_positive`, we try to get matchable threshold by comparing the label of estimated object.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix: compute matchable threshold from estimation label if gt label is FP

perception_eval/perception_eval/evaluation/matching/objects_filter.py, perception_eval/perception_eval/evaluation/result/object_result.py, perception_eval/perception_eval/evaluation/result/perception_pass_fail_result.py
This PR fixes how to count FP and TN in fp_validation.
And add method to get number of GT.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(perception): fix how to count FP and TN in fp_validation and add method to get number of GT

perception_eval/perception_eval/evaluation/result/perception_frame_result.py
This PR adds `self.pass_fail_result` in `PerceptionFrameResult` for pickle.
In perception_eval, it is possible to analyze perception using pickled `PerceptionFrameResult` ([docs](https://github.com/tier4/autoware_perception_evaluation/blob/develop/docs/en/perception/analyzer.md#how-to-use)). But if not exist (save) `self.pass_fail_result` in it, impossible to re-generate the result. So I added this instance variable.
Note that we will deal with the pickling of PassFailResult later, as it is complicated.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> feat(perception): add pass_fail_result for pickle

perception_eval/perception_eval/common/label.py, perception_eval/perception_eval/visualization/eda_tool.py, perception_eval/test/common/test_label.py
This PR fixes the number of GTs when finished loading dataset.
In previous, use `LabelConverter.convert_name` to load just target_labels. (https://github.com/tier4/autoware_perception_evaluation/blob/develop/perception_eval/perception_eval/config/perception_evaluation_config.py#L134) But then the number of GTs was increased fraudulently.
In order to fix this problem, I performed below things.
- Do not count up in `convert_name`
- `convert_label` and `convert_name` is similar function. Therefore, I changed it to a function that can be used for different purposes. 
- change the function name from `convert_name` to `convert_name_without_count` to be the  clearer
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix(perception): delete unnecessary count up method in `LabelConverter`

perception_eval/perception_eval/config/_evaluation_config_base.py
Described in https://github.com/tier4/autoware_perception_evaluation/issues/236.
`mkdir` statement want to create invalid or permission-denied folder even during loading pickle file.
This PR is quick fix for reading pickle file issue.
<details>
<pre>
<code>
</code>
</pre>
</details>
<details>
<pre>
<code>
</code>
</pre>
</details>
=> fix: add simple escape in mkdir sequense
